Repository Futura-Py/TimerX, pull requests merged in 2022-01, with the labels that each got.

#37 fix: gp and feat: Commitizen and pre-commit hooks
  .gitpod.yml
  .isort.cfg
  .pre-commit-config.yaml
  pyproject.toml
  pyvenv.cfg
  requirements-dev.txt
Labels: enhancement, approved

#41 feat(docs, netlify): Netlify Configuration
  netlify.toml
Labels: enhancement, ready, approved

#39 Readme Overhaul
  CONTRIBUTING.md
  README.md
Labels: documentation, approved

#40 feat: Dynamic Resizing
  README.md
  main.py
Labels: ready

#42 chore(docs): Update+add documentation
  .github/workflows/main.yml
  CONTRIBUTING.md
  docs/docs/CONTRIBUTING.md
  docs/docs/compile.md
  docs/docs/intro.md
  docs/docusaurus.config.js
Labels: documentation, enhancement, ready

#48 docs: Adhere to new org change
  docs/docusaurus.config.js
Labels: documentation

#54 style(docs): Prettier formatting
  .gitignore
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/LICENSE
  docs/README.md
  docs/babel.config.js
  docs/docs/CONTRIBUTING.md
  docs/docs/compile.md
  docs/docs/intro.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/components/HomepageFeatures.js
  docs/src/css/custom.css
  docs/src/pages/HomepageFeatures.js
  docs/src/pages/index.js
  docs/yarn.lock
Labels: documentation, ready

#57 chore: Repository Cleanup
  .gitignore
  .vscode/.ropeproject/config.py
  .vscode/.ropeproject/objectdb
  .vscode/launch.json
  .vscode/settings.json
  README.md
  Scripts/Activate.ps1
  Scripts/activate
  Scripts/activate.bat
  Scripts/deactivate.bat
  Scripts/pip.exe
  Scripts/pip3.10.exe
  Scripts/pip3.exe
  Scripts/python.exe
  Scripts/pythonw.exe
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/babel.config.js
  docs/docs/CONTRIBUTING.md
  docs/docs/compile.md
  docs/docs/intro.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/components/HomepageFeatures.js
  docs/src/css/custom.css
  docs/src/pages/HomepageFeatures.js
  docs/src/pages/index.js
  docs/yarn.lock
  main.py
  setup.py
  utils.py
Labels: approved

#70 feat: Re-add System Theme
  main.py
Labels: bug, ready

#72 docs: Update Screenshot in README.md
  README.md
  assets/logo.icns
  assets/logo.ico
  assets/logo.png
  assets/readme/dark.png
  assets/readme/light.png
  pyvenv.cfg
Labels: ready
