Repository Futura-Py/TimerX, pull requests merged in 2022-02, with the labels that each got.

#73 perf: Fix performance
  main.py
  setup.py
Labels: enhancement, ready

#79 docs: Replace org name(yet again)
  LICENSE
  README.md
  docs/docusaurus.config.js
  docs/src/pages/index.js
  main.py
Labels: documentation, ready

#75 docs: macOS support with WineHQ
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/build.yml
  .github/workflows/release-all.yml
  .github/workflows/release-mac.yml
  .github/workflows/release-ubuntu.yml
  .github/workflows/release-windows.yml
  .gitpod.yml
  .isort.cfg
  .pre-commit-config.yaml
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/docs/macos-winehq.mdx
  docs/package.json
  docs/yarn.lock
  package-lock.json
  package.json
Labels: documentation, ready

#83 feat: Update System
  assets/images/dark/update.png
  main.py
  utils.py
Labels: enhancement, ready

#94 feat: Mica
  main.py
  requirements.txt
Labels: enhancement, ready

#98 fix(bug97): modify setAlwaysOnTop() to somehow allow theme switches
  .pre-commit-config.yaml
  main.py
  setup.py
Labels: ready
